  name: master
  on:
    push:
      branches:
        - master
        - dev
  jobs:
    push-to-repo:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [ '3.10', '3.11' ]
      steps:
        - uses: actions/checkout@v3
        - name: Setup Python ${{matrix.python-version}}
          uses: actions/setup-python@v4
          with:
            python-version: ${{matrix.python-version}}
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip setuptools
            pip install pytest
            pip install -e .[s3]
            if [-f requirements.txt]; then pip install -r requirements.txt; fi
        - name: Run Tests
          run: pytest tests
